#! /bin/bash

PKG=__PACKAGE__
USERNAME=__PACKAGE_USER__
USERID=__PACKAGE_USERID__
GROUPNAME=__PACKAGE_USERGROUP__
GROUPID=__PACKAGE_USERGROUPID__

#create users if they don't exist
if ! getent group $GROUPNAME > /dev/null; then
  groupadd -g $GROUPID $GROUPNAME || echo "$PKG : Adding group $GROUPNAME <<FAILURE>>"| tee -a /var/log/dpkg.log || true
fi

if ! getent passwd $USERID > /dev/null; then
  useradd -g $GROUPID -u $USERID $USERNAME || echo "$PKG : Adding user $USERNAME <<FAILURE>>" | tee -a /var/log/dpkg.log || true
fi