#!/bin/bash

PACKAGE=__PACKAGE__
USERNAME=__PACKAGE_USER__
LOG_DIR=__LOG_DIR__
LOG_FILENAME=__LOG_FILENAME__
LOG_FILEPATH=__LOG_FILEPATH__

DEPLOYMENT_MODE="client"
if [ $DEPLOYMENT_MODE == "cluster" ]
 then
   PORT=6066
 else
   PORT=7077
fi

SPARK_MASTER="spark://10.52.18.196:$PORT,10.51.18.184:$PORT"
DRIVER_MEMORY="1g"
SPARK_EXECUTOR_INSTANCES=8
EXECUTOR_CORES=5
DRIVER_OPTIONS="-Dlog4j.configuration=file:/var/lib/fk-pf-spark/conf/log4j-viesti-compass-streaming.properties \
                -Dcom.sun.management.jmxremote.port=46697 \
                -Dcom.sun.management.jmxremote.authenticate=false \
                -Dcom.sun.management.jmxremote.ssl=false \
                -Djava.net.preferIPv4Stack=true"

CLASS="com.flipkart.StreamingAppV3"
JAR_PATH="/usr/share/spark/jars/fk-ekl-spark-jobs.jar"
CONFIG_SERVICE_ENDPOINT=10.24.0.32
CONFIG_SERVICE_PORT=80

submit_streaming_app_v3(){
  echo "Submitting StreamingAppV3 in $DEPLOYMENT_MODE Mode..."
  sudo -u ${USERNAME} APP_ENV="hyd" \
       CONFIG_SERVICE_ENDPOINT=$CONFIG_SERVICE_ENDPOINT \
       CONFIG_SERVICE_PORT=$CONFIG_SERVICE_PORT \
       /var/lib/fk-pf-spark/bin/spark-submit \
       --deploy-mode $DEPLOYMENT_MODE \
       --supervise \
       --driver-class-path $JAR_PATH \
       --conf spark.dynamicAllocation.enabled=false \
       --conf spark.driver.extraJavaOptions="$DRIVER_OPTIONS" \
       --conf spark.executor.instances=$SPARK_EXECUTOR_INSTANCES \
       --executor-cores $EXECUTOR_CORES \
       --driver-memory $DRIVER_MEMORY \
       --master $SPARK_MASTER \
       --class $CLASS \
       /var/lib/fk-ekl-spark-jobs/fk-ekl-spark-jobs.jar &
}

case "$1" in
  start)
    ulimit -n 10000
    submit_streaming_app_v3
  ;;
  stop)
    kill -s SIGTERM `pgrep -f StreamingAppV3`
    sleep 30
  ;;
  force_kill)
    pkill -9 -f "StreamingAppV3"
  ;;
  restart)
    kill -s SIGTERM `pgrep -f StreamingAppV3`
    sleep 30
    ulimit -n 10000
    submit_streaming_app_v3
  ;;
  *)
    echo "Usage $0 {start|stop|restart|status}"
    exit 3
  ;;
esac