[template]
prefix="/__BUCKET__"
src = "log4j.viesti.compass.streaming.tmpl"
dest = "/var/lib/fk-pf-spark/conf/log4j-viesti-compass-streaming.properties.url"
keys = [
	"/log4j.viesti.compass.streaming"
]

uid = 3069
gid = 3000
mode = "0644"

#reload_cmd = "/etc/init.d/__PACKAGE_BIGFOOT__ stop; sleep 5; /etc/init.d/__PACKAGE_BIGFOOT__ start"
reload_cmd = "curl `cat /var/lib/fk-pf-spark/conf/log4j-viesti-compass-streaming.properties.url` > /var/lib/fk-pf-spark/conf/log4j-viesti-compass-streaming.properties"